<a href="https://colab.research.google.com/github/komalimotupalli/Insider_Risk_Detection/blob/main/Insider_Risk_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/psychometric.csv')

In [ ]:
df.head()

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

In [ ]:
X=df[['O','C','E','A','N']]
X.head()

    O   C   E   A   N
0  40  39  36  19  40
1  26  22  17  39  32
2  22  16  23  40  33
3  40  48  36  14  37
4  36  44  23  44  25

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=100,
    contamination=0.1,
    random_state=42
)

model.fit(X_scaled)

IsolationForest(contamination=0.1, random_state=42)

In [ ]:
df['risk_flag'] = model.predict(X_scaled)
df.head()

             employee_name  user_id   O   C   E   A   N  risk_flag
0         Calvin Edan Love  CEL0561  40  39  36  19  40          1
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32          1
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33          1
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37          1
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25          1

In [ ]:
risky_employees = df[df['risk_flag'] == -1]
risky_employees

               employee_name  user_id   O   C   E   A   N  risk_flag
13          Grant Camden Gay  GCG0951  33  33  25  19  44         -1
21         Gray Mason Fulton  GMF0738  30  40  45  20  18         -1
25       Blaine Jelani Weeks  BJW0619  30  43  47  21  39         -1
41      Olivia Rose Galloway  ORG0339  50  28  46  47  20         -1
50         Kai Penelope Peck  KPP0452  44  46  44  16  19         -1
..                       ...      ...  ..  ..  ..  ..  ..        ...
956        Mira Jamalia Snow  MJS0890  10  26  16  11  29         -1
981     Bell Jorden Martinez  BJM0111  22  24  39  41  19         -1
989    Brenda Alika Matthews  BAM0636  13  40  46  42  39         -1
993    Aquila Tanner Ellison  ATE0869  13  15  40  44  33         -1
994  Isadora Blaine Shepherd  IBS0836  10  44  50  38  27         -1

[100 rows x 8 columns]